---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/cogcloudapps_development
    username: app
    password: app
  jpa:
    hibernate.ddl-auto: none
show_sql: false